"""sync models to database no wargear options or unit composition but is ok

Revision ID: 4d11667fc685
Revises: 0ea7f84671ce
Create Date: 2026-02-07 14:43:57.191950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d11667fc685'
down_revision: Union[str, Sequence[str], None] = '0ea7f84671ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('faction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('toughness', sa.Integer(), nullable=False),
    sa.Column('save', sa.Integer(), nullable=False),
    sa.Column('wounds', sa.Integer(), nullable=False),
    sa.Column('leadership', sa.Integer(), nullable=False),
    sa.Column('objective_control', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abilities_unit_id'), 'abilities', ['unit_id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keyword_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_unit_id'), 'keywords', ['unit_id'], unique=False)
    op.create_table('weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapons_unit_id'), 'weapons', ['unit_id'], unique=False)
    op.create_table('weapon_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('range_inches', sa.Integer(), nullable=False),
    sa.Column('attacks', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weapon_strength', sa.Integer(), nullable=False),
    sa.Column('save', sa.Integer(), nullable=False),
    sa.Column('armour_penetration', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapon_profiles_weapon_id'), 'weapon_profiles', ['weapon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weapon_profiles_weapon_id'), table_name='weapon_profiles')
    op.drop_table('weapon_profiles')
    op.drop_index(op.f('ix_weapons_unit_id'), table_name='weapons')
    op.drop_table('weapons')
    op.drop_index(op.f('ix_keywords_unit_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_abilities_unit_id'), table_name='abilities')
    op.drop_table('abilities')
    op.drop_table('units')
    # ### end Alembic commands ###
