"""initial schema

Revision ID: 61c99176b574
Revises: 
Create Date: 2026-06-29 16:35:09.411408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61c99176b574'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factions_name'), 'factions', ['name'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('weapons',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('range_inches', sa.Integer(), nullable=True),
    sa.Column('attacks', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('weapon_skill', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('armor_piercing', sa.Integer(), nullable=False),
    sa.Column('damage', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.CheckConstraint("category IN ('range', 'melee')", name='ck_weapon_category'),
    sa.CheckConstraint('range_inches IS NULL OR range_inches >= 0', name='ck_weapon_range_non_negative'),
    sa.CheckConstraint('weapon_skill >= 0 AND strength >= 0 AND armor_piercing >= 0', name='ck_weapon_stats_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subfactions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('faction_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faction_id', 'name')
    )
    op.create_index(op.f('ix_subfactions_faction_id'), 'subfactions', ['faction_id'], unique=False)
    op.create_table('armies',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('faction_id', sa.Uuid(), nullable=False),
    sa.Column('subfaction_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subfaction_id'], ['subfactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_armies_faction_id'), 'armies', ['faction_id'], unique=False)
    op.create_index(op.f('ix_armies_owner_user_id'), 'armies', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_armies_subfaction_id'), 'armies', ['subfaction_id'], unique=False)
    op.create_table('units',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('faction_id', sa.Uuid(), nullable=False),
    sa.Column('subfaction_id', sa.Uuid(), nullable=True),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('toughness', sa.Integer(), nullable=False),
    sa.Column('armor_save', sa.Integer(), nullable=False),
    sa.Column('wounds', sa.Integer(), nullable=False),
    sa.Column('invulnerable_save', sa.Integer(), nullable=True),
    sa.Column('leadership', sa.Integer(), nullable=False),
    sa.Column('objective_control', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.CheckConstraint('invulnerable_save IS NULL OR invulnerable_save >= 0', name='ck_unit_invuln_non_negative'),
    sa.CheckConstraint('movement >= 0 AND toughness >= 0 AND armor_save >= 0 AND wounds >= 0 AND leadership >= 0 AND objective_control >= 0 AND points >= 0', name='ck_unit_stats_non_negative'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.ForeignKeyConstraint(['subfaction_id'], ['subfactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_faction_id'), 'units', ['faction_id'], unique=False)
    op.create_index(op.f('ix_units_subfaction_id'), 'units', ['subfaction_id'], unique=False)
    op.create_index(op.f('ix_units_unit_name'), 'units', ['unit_name'], unique=False)
    op.create_table('army_units',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('army_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_army_unit_amount_non_negative'),
    sa.ForeignKeyConstraint(['army_id'], ['armies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('army_id', 'unit_id')
    )
    op.create_index(op.f('ix_army_units_army_id'), 'army_units', ['army_id'], unique=False)
    op.create_index(op.f('ix_army_units_unit_id'), 'army_units', ['unit_id'], unique=False)
    op.create_table('unit_abilities',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('ability_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id', 'ability_id')
    )
    op.create_table('unit_weapons',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('weapon_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id', 'weapon_id')
    )
    op.create_table('user_unit',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_user_unit_amount_non_negative'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'unit_id')
    )
    op.create_index(op.f('ix_user_unit_owner_user_id'), 'user_unit', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_user_unit_unit_id'), 'user_unit', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_unit_unit_id'), table_name='user_unit')
    op.drop_index(op.f('ix_user_unit_owner_user_id'), table_name='user_unit')
    op.drop_table('user_unit')
    op.drop_table('unit_weapons')
    op.drop_table('unit_abilities')
    op.drop_index(op.f('ix_army_units_unit_id'), table_name='army_units')
    op.drop_index(op.f('ix_army_units_army_id'), table_name='army_units')
    op.drop_table('army_units')
    op.drop_index(op.f('ix_units_unit_name'), table_name='units')
    op.drop_index(op.f('ix_units_subfaction_id'), table_name='units')
    op.drop_index(op.f('ix_units_faction_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_armies_subfaction_id'), table_name='armies')
    op.drop_index(op.f('ix_armies_owner_user_id'), table_name='armies')
    op.drop_index(op.f('ix_armies_faction_id'), table_name='armies')
    op.drop_table('armies')
    op.drop_index(op.f('ix_subfactions_faction_id'), table_name='subfactions')
    op.drop_table('subfactions')
    op.drop_table('weapons')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_factions_name'), table_name='factions')
    op.drop_table('factions')
    op.drop_table('abilities')
    # ### end Alembic commands ###
