"""add kill team catalog

Revision ID: 798274facc83
Revises: 44441c6a9671
Create Date: 2026-09-19 14:09:03.369304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '798274facc83'
down_revision: Union[str, Sequence[str], None] = '44441c6a9671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kt_factions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kt_factions_name'), 'kt_factions', ['name'], unique=True)
    op.create_table('kt_kill_teams',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('faction_id', sa.Uuid(), nullable=False),
    sa.Column('operative_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('operative_count >= 1', name='ck_kt_kill_team_operative_count'),
    sa.ForeignKeyConstraint(['faction_id'], ['kt_factions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kt_kill_teams_faction_id'), 'kt_kill_teams', ['faction_id'], unique=False)
    op.create_index(op.f('ix_kt_kill_teams_name'), 'kt_kill_teams', ['name'], unique=True)
    op.create_table('kt_kill_team_rules',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kill_team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['kill_team_id'], ['kt_kill_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kill_team_id', 'name')
    )
    op.create_index(op.f('ix_kt_kill_team_rules_kill_team_id'), 'kt_kill_team_rules', ['kill_team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kt_kill_team_rules_kill_team_id'), table_name='kt_kill_team_rules')
    op.drop_table('kt_kill_team_rules')
    op.drop_index(op.f('ix_kt_kill_teams_name'), table_name='kt_kill_teams')
    op.drop_index(op.f('ix_kt_kill_teams_faction_id'), table_name='kt_kill_teams')
    op.drop_table('kt_kill_teams')
    op.drop_index(op.f('ix_kt_factions_name'), table_name='kt_factions')
    op.drop_table('kt_factions')
    # ### end Alembic commands ###
