"""add kill team catalog

Revision ID: 93949938b92e
Revises: 44441c6a9671
Create Date: 2026-09-22 18:39:21.912760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93949938b92e'
down_revision: Union[str, Sequence[str], None] = '44441c6a9671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kt_factions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kt_factions_name'), 'kt_factions', ['name'], unique=True)
    op.create_table('kt_kill_teams',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('faction_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['kt_factions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kt_kill_teams_faction_id'), 'kt_kill_teams', ['faction_id'], unique=False)
    op.create_index(op.f('ix_kt_kill_teams_name'), 'kt_kill_teams', ['name'], unique=True)
    op.create_table('kt_equipment',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kill_team_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['kill_team_id'], ['kt_kill_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kill_team_id', 'name')
    )
    op.create_index(op.f('ix_kt_equipment_kill_team_id'), 'kt_equipment', ['kill_team_id'], unique=False)
    op.create_index('uq_kt_equipment_universal_name', 'kt_equipment', ['name'], unique=True, sqlite_where=sa.text('kill_team_id IS NULL'), postgresql_where=sa.text('kill_team_id IS NULL'))
    op.create_table('kt_kill_team_rules',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kill_team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['kill_team_id'], ['kt_kill_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kill_team_id', 'name')
    )
    op.create_index(op.f('ix_kt_kill_team_rules_kill_team_id'), 'kt_kill_team_rules', ['kill_team_id'], unique=False)
    op.create_table('kt_operatives',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kill_team_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('apl', sa.Integer(), nullable=False),
    sa.Column('move', sa.Integer(), nullable=False),
    sa.Column('save', sa.Integer(), nullable=False),
    sa.Column('wounds', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.CheckConstraint('apl >= 1', name='ck_kt_operative_apl'),
    sa.CheckConstraint('move >= 0 AND save >= 0 AND wounds >= 0', name='ck_kt_operative_stats_non_negative'),
    sa.ForeignKeyConstraint(['kill_team_id'], ['kt_kill_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kill_team_id', 'name')
    )
    op.create_index(op.f('ix_kt_operatives_kill_team_id'), 'kt_operatives', ['kill_team_id'], unique=False)
    op.create_index(op.f('ix_kt_operatives_name'), 'kt_operatives', ['name'], unique=False)
    op.create_table('kt_ploys',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kill_team_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('cp_cost', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("kind IN ('strategy', 'firefight')", name='ck_kt_ploy_kind'),
    sa.CheckConstraint('cp_cost >= 0', name='ck_kt_ploy_cp_cost'),
    sa.ForeignKeyConstraint(['kill_team_id'], ['kt_kill_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kill_team_id', 'name')
    )
    op.create_index(op.f('ix_kt_ploys_kill_team_id'), 'kt_ploys', ['kill_team_id'], unique=False)
    op.create_index('uq_kt_ploy_universal_name', 'kt_ploys', ['name'], unique=True, sqlite_where=sa.text('kill_team_id IS NULL'), postgresql_where=sa.text('kill_team_id IS NULL'))
    op.create_table('kt_selection_lists',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kill_team_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('restriction_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('budget >= 1', name='ck_kt_selection_list_budget'),
    sa.CheckConstraint('position >= 0', name='ck_kt_selection_list_position'),
    sa.ForeignKeyConstraint(['kill_team_id'], ['kt_kill_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kill_team_id', 'position')
    )
    op.create_index(op.f('ix_kt_selection_lists_kill_team_id'), 'kt_selection_lists', ['kill_team_id'], unique=False)
    op.create_table('kt_abilities',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operative_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['operative_id'], ['kt_operatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operative_id', 'name')
    )
    op.create_index(op.f('ix_kt_abilities_operative_id'), 'kt_abilities', ['operative_id'], unique=False)
    op.create_table('kt_selection_options',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('selection_list_id', sa.Uuid(), nullable=False),
    sa.Column('operative_id', sa.Uuid(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('models', sa.Integer(), nullable=False),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.Column('loadout_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('cost >= 1', name='ck_kt_selection_option_cost'),
    sa.CheckConstraint('max_selections IS NULL OR max_selections >= 1', name='ck_kt_selection_option_max_selections'),
    sa.CheckConstraint('models >= 1', name='ck_kt_selection_option_models'),
    sa.ForeignKeyConstraint(['operative_id'], ['kt_operatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selection_list_id'], ['kt_selection_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selection_list_id', 'operative_id')
    )
    op.create_index(op.f('ix_kt_selection_options_operative_id'), 'kt_selection_options', ['operative_id'], unique=False)
    op.create_index(op.f('ix_kt_selection_options_selection_list_id'), 'kt_selection_options', ['selection_list_id'], unique=False)
    op.create_table('kt_selection_restrictions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('selection_list_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('max_operatives', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_operatives >= 1', name='ck_kt_selection_restriction_max'),
    sa.ForeignKeyConstraint(['selection_list_id'], ['kt_selection_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selection_list_id', 'keyword')
    )
    op.create_index(op.f('ix_kt_selection_restrictions_keyword'), 'kt_selection_restrictions', ['keyword'], unique=False)
    op.create_index(op.f('ix_kt_selection_restrictions_selection_list_id'), 'kt_selection_restrictions', ['selection_list_id'], unique=False)
    op.create_table('kt_weapons',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operative_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('range', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('attacks', sa.Integer(), nullable=False),
    sa.Column('hit', sa.Integer(), nullable=False),
    sa.Column('normal_damage', sa.Integer(), nullable=False),
    sa.Column('crit_damage', sa.Integer(), nullable=False),
    sa.Column('weapon_rules', sa.JSON(), nullable=False),
    sa.CheckConstraint("category IN ('range', 'melee')", name='ck_kt_weapon_category'),
    sa.CheckConstraint('attacks >= 0 AND hit >= 0 AND normal_damage >= 0 AND crit_damage >= 0', name='ck_kt_weapon_stats_non_negative'),
    sa.CheckConstraint('range >= 1', name='ck_kt_weapon_range'),
    sa.ForeignKeyConstraint(['operative_id'], ['kt_operatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operative_id', 'name')
    )
    op.create_index(op.f('ix_kt_weapons_operative_id'), 'kt_weapons', ['operative_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kt_weapons_operative_id'), table_name='kt_weapons')
    op.drop_table('kt_weapons')
    op.drop_index(op.f('ix_kt_selection_restrictions_selection_list_id'), table_name='kt_selection_restrictions')
    op.drop_index(op.f('ix_kt_selection_restrictions_keyword'), table_name='kt_selection_restrictions')
    op.drop_table('kt_selection_restrictions')
    op.drop_index(op.f('ix_kt_selection_options_selection_list_id'), table_name='kt_selection_options')
    op.drop_index(op.f('ix_kt_selection_options_operative_id'), table_name='kt_selection_options')
    op.drop_table('kt_selection_options')
    op.drop_index(op.f('ix_kt_abilities_operative_id'), table_name='kt_abilities')
    op.drop_table('kt_abilities')
    op.drop_index(op.f('ix_kt_selection_lists_kill_team_id'), table_name='kt_selection_lists')
    op.drop_table('kt_selection_lists')
    op.drop_index('uq_kt_ploy_universal_name', table_name='kt_ploys', sqlite_where=sa.text('kill_team_id IS NULL'), postgresql_where=sa.text('kill_team_id IS NULL'))
    op.drop_index(op.f('ix_kt_ploys_kill_team_id'), table_name='kt_ploys')
    op.drop_table('kt_ploys')
    op.drop_index(op.f('ix_kt_operatives_name'), table_name='kt_operatives')
    op.drop_index(op.f('ix_kt_operatives_kill_team_id'), table_name='kt_operatives')
    op.drop_table('kt_operatives')
    op.drop_index(op.f('ix_kt_kill_team_rules_kill_team_id'), table_name='kt_kill_team_rules')
    op.drop_table('kt_kill_team_rules')
    op.drop_index('uq_kt_equipment_universal_name', table_name='kt_equipment', sqlite_where=sa.text('kill_team_id IS NULL'), postgresql_where=sa.text('kill_team_id IS NULL'))
    op.drop_index(op.f('ix_kt_equipment_kill_team_id'), table_name='kt_equipment')
    op.drop_table('kt_equipment')
    op.drop_index(op.f('ix_kt_kill_teams_name'), table_name='kt_kill_teams')
    op.drop_index(op.f('ix_kt_kill_teams_faction_id'), table_name='kt_kill_teams')
    op.drop_table('kt_kill_teams')
    op.drop_index(op.f('ix_kt_factions_name'), table_name='kt_factions')
    op.drop_table('kt_factions')
    # ### end Alembic commands ###
